<#
.SYNOPSIS
    Posts player-facing release notes from build/release_notes.md to Discord.

.DESCRIPTION
    Reads the Discord webhook URL from the .env file at the project root.
    Reads pre-written release notes from build/release_notes.md (generated by the
    release-ops agent), wraps them in a Discord embed, and posts to the configured
    webhook. Updates release_state.json with the current HEAD commit after posting.

    The release-ops agent is responsible for writing build/release_notes.md with
    polished, player-relevant content before running this script.

.PARAMETER NotesFile
    Path to the release notes markdown file. Defaults to build/release_notes.md.

.PARAMETER DryRun
    Print the notes to console without posting to Discord or updating state.

.EXAMPLE
    .\push_release_notes.ps1
    .\push_release_notes.ps1 -DryRun
    .\push_release_notes.ps1 -NotesFile "build\release_notes_v0.2.0.md"
#>
param(
    [string]$NotesFile = "",
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

$projectPath = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$envFile     = Join-Path $projectPath ".env"
$stateFile   = Join-Path $PSScriptRoot "release_state.json"

# ==========================================================================
# Load .env — reads KEY=VALUE pairs, strips quotes and comments
# ==========================================================================

function Read-EnvFile($path) {
    $vars = @{}
    if (-not (Test-Path $path)) { return $vars }
    foreach ($line in Get-Content $path) {
        $line = $line.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) { continue }
        $parts = $line -split "=", 2
        if ($parts.Count -ne 2) { continue }
        $key   = $parts[0].Trim()
        $value = $parts[1].Trim().Trim('"').Trim("'")
        $vars[$key] = $value
    }
    return $vars
}

$env_vars   = Read-EnvFile $envFile
$webhookUrl = $env_vars["DISCORD_DEPLOY_WEBHOOK"]

if ([string]::IsNullOrWhiteSpace($webhookUrl)) {
    Write-Error @"
Discord webhook URL not found.
Create a .env file at the project root with:

    DISCORD_DEPLOY_WEBHOOK=https://discord.com/api/webhooks/ID/TOKEN

The .env file is gitignored — never commit it.
"@
    exit 1
}

# ==========================================================================
# Release State — tracks version, summary, and last-posted commit SHA
# ==========================================================================

function Get-ReleaseState {
    if (Test-Path $stateFile) {
        $raw = Get-Content $stateFile -Raw | ConvertFrom-Json
        return @{
            version              = if ($raw.version)              { [string]$raw.version }              else { "0.1.0" }
            summary              = if ($raw.summary)              { [string]$raw.summary }              else { "Playtest build" }
            last_deployed_commit = if ($raw.last_deployed_commit) { [string]$raw.last_deployed_commit } else { "" }
            last_build_id        = if ($raw.last_build_id)        { [string]$raw.last_build_id }        else { "" }
            last_deploy_time     = if ($raw.last_deploy_time)     { [string]$raw.last_deploy_time }     else { "" }
        }
    }
    return @{
        version              = "0.1.0"
        summary              = "Playtest build"
        last_deployed_commit = ""
        last_build_id        = ""
        last_deploy_time     = ""
    }
}

function Save-ReleaseState($state) {
    [PSCustomObject]@{
        version              = $state.version
        summary              = $state.summary
        last_deployed_commit = $state.last_deployed_commit
        last_build_id        = $state.last_build_id
        last_deploy_time     = $state.last_deploy_time
    } | ConvertTo-Json -Depth 3 | Set-Content -Path $stateFile -Encoding UTF8
}

# ==========================================================================
# Read Release Notes File
# ==========================================================================

# Resolve notes file path
if ([string]::IsNullOrWhiteSpace($NotesFile)) {
    $NotesFile = Join-Path (Join-Path $projectPath "build") "release_notes.md"
}
if (-not [System.IO.Path]::IsPathRooted($NotesFile)) {
    $NotesFile = Join-Path $projectPath $NotesFile
}

if (-not (Test-Path $NotesFile)) {
    Write-Error @"
Release notes file not found: $NotesFile

The release-ops agent must write build/release_notes.md before running this script.
"@
    exit 1
}

$notesContent = (Get-Content $NotesFile -Raw -Encoding UTF8).Trim()
if ($notesContent.Length -lt 10) {
    Write-Error "Release notes file is empty or too short: $NotesFile"
    exit 1
}

# Strip the markdown H1 title line — it becomes the embed title instead
$description = $notesContent -replace '^#\s+.+\r?\n\s*', ''
$description = $description.Trim()

function Get-CurrentCommitSha {
    try {
        $sha = & git -C "$projectPath" rev-parse HEAD 2>&1
        if ($LASTEXITCODE -eq 0 -and $sha -match '^[0-9a-f]{40}') { return $sha.Trim() }
    } catch {}
    return ""
}

# ==========================================================================
# Main
# ==========================================================================

$state   = Get-ReleaseState
$version = $state.version
$summary = $state.summary

Write-Output ""
Write-Output "=== Release Notes - v${version} ==="
Write-Output "Reading from: $NotesFile"
Write-Output ""
Write-Output $notesContent

if ($DryRun) {
    Write-Output ""
    Write-Output "[DryRun] Skipping Discord post and state update."
    exit 0
}

# ==========================================================================
# Discord Embed
# ==========================================================================

# Truncate if over Discord embed limit
if ($description.Length -gt 4000) { $description = $description.Substring(0, 3997) + "..." }

$payload = [ordered]@{
    username   = "Space Game Updates"
    avatar_url = "https://cdn.discordapp.com/embed/avatars/0.png"
    embeds     = @(
        [ordered]@{
            title       = ":rocket: Playtest Update - v${version}"
            description = $description
            color       = [int]0x9B59B6
            fields      = @(
                [ordered]@{
                    name   = "Summary"
                    value  = $summary
                    inline = $false
                }
            )
            footer    = [ordered]@{ text = "Super Cool Space Game" }
            timestamp = (Get-Date -Format "o")
        }
    )
}

$body  = $payload | ConvertTo-Json -Depth 10 -Compress
$bytes = [System.Text.Encoding]::UTF8.GetBytes($body)

Write-Output ""
Write-Output "=== Posting to Discord ==="

for ($attempt = 1; $attempt -le 3; $attempt++) {
    try {
        $resp = Invoke-WebRequest -Uri $webhookUrl -Method POST `
            -ContentType "application/json; charset=utf-8" `
            -Body $bytes -UseBasicParsing -ErrorAction Stop
        Write-Output "Posted successfully (HTTP $($resp.StatusCode))"
        break
    } catch {
        $status = $_.Exception.Response.StatusCode.value__
        if ($attempt -lt 3) {
            $delay = if ($status -eq 429) { 5 } else { 2 }
            Write-Warning "Attempt $attempt failed (HTTP $status) - retrying in ${delay}s..."
            Start-Sleep -Seconds $delay
        } else {
            Write-Error "Failed to post to Discord after 3 attempts: $($_.Exception.Message)"
            exit 1
        }
    }
}

# ==========================================================================
# Update State - only after successful post
# ==========================================================================

$state.last_deployed_commit = Get-CurrentCommitSha
$state.last_deploy_time     = (Get-Date -Format "yyyy-MM-dd HH:mm")
Save-ReleaseState $state

$newShort = if ($state.last_deployed_commit) { $state.last_deployed_commit.Substring(0, [Math]::Min(7, $state.last_deployed_commit.Length)) } else { "(unknown)" }
Write-Output ""
Write-Output "State updated. Next run will cover commits since: $newShort"
exit 0
